aliases: []
creation_timestamp: 1754401355514
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1754401355514
metrics: null
model_id: m-508a348554664cbbbdbc7441e0245da8
name: loan_risk_lightgbm
params: null
run_id: a0768566e87f4ad2aa18bae9050c5d43
run_link: null
source: models:/m-508a348554664cbbbdbc7441e0245da8
status: READY
status_message: null
storage_location: dbfs:/databricks/mlflow-tracking/1274522946844847/logged_models/m-508a348554664cbbbdbc7441e0245da8/artifacts
user_id: null
version: 1
